addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: f4ee4f35-dd3f-4ee1-bc22-1567af83503b
after_success:
- ./df-build.sh
install: mvn install -q -DskipTests=true
jdk:
- oraclejdk8
language: java
notifications: {}
script: mvn test -q
services:
- mongodb
- riak
sudo: false
# Modified by Insights Service at 2016-05-20 04:27:27.575355
